Component/select
bristol-tech-fair/btf-frontend pull request #28
Opened 2021-01-18 16:23 UTC by vixhez

#10 

Made some progress with the select component. Initial styling - border, basic layout, padding inside component. Work still to be done on drop down arrow styling.

2021-01-18 22:11 UTC, RobTF9 commented
Good progress! Before I recommend changes though can you target this pull request at the `develop` branch as opposed to `main`?

2021-01-19 11:36 UTC, vixhez commented
All sorted!

2021-01-19 12:53 UTC, RobTF9 requested changes

2021-01-19 12:53 UTC, RobTF9 commented on src/components/Select/Select.jsx
> +export default Select;
A few issues with this file: 
• Don't hard code the options in like that, pass them in as an array and map over them.
• I would change `SelectDropdown` to a `select` element and style it with a nested selector (see comments on Selectstyles.js).
• The `value` prop is not a value, rather the label text. Consider changing this `label`.
• Don't hard code the name of the select, pass it in as a prop called `name`.
• You need to pass in an `onChange` handler.
• Pass in a `defaultValue` prop.

So with the above in mind it should end up looking something like this:
```
const Select = ({ label, name, options, onChange, defaultValue }) => {
    return (
        <SelectWrapper>
            <label htmlFor={name}>{label}</label>
            <select
                name={name}
                id={name}
                onChange={onChange}
                value={defaultValue}
            >
                {options.map(({ value, label }, index)  =>  (
                     <option
                        key={value + index}
                        className="select--option"
                        value={value}
                       >
                          {label}
                     </option>
                ))}
            </select>
        </SelectWrapper>
    )
};

Select.propTypes = {
  name: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired,
  defaultValue: PropTypes.string,
  options: PropTypes.arrayOf(
    PropTypes.shape({
      value: PropTypes.string.isRequired,
      label: PropTypes.string.isRequired,
    })
  ).isRequired,
  onChange: PropTypes.func.isRequired,
};
```

2021-01-19 12:53 UTC, RobTF9 commented on src/components/Select/Select.stories.jsx
> +export const HelloWorld = () => <Select value="Example label" />;
Update this file to show a few variations using the different props you add in the main jsx file.

2021-01-19 12:53 UTC, RobTF9 commented on src/components/Select/Select.styles.js
> +`;
As mention in comments above a few changes to make here:

- You shouldn't use pixel values, we're using rem for sizing so change border-radius to `0.4rem`.
- Don't need a max-width, width, padding left or display.
- Nest the select in `SelectWrapper`.
- Create a dropdown arrow with the `::after` pseudo select (https://css-tricks.com/snippets/css/css-triangle/ great resource for creating triangles with css.
- Remove default dropdown arrow with `-moz-appearance: none;` and `-webkit-appearance: none;` 
- Position the items within the `SelectWrapper` with flexbox.
- Add correct padding values to select.

You should end up with something like this:
```
import styled from 'styled-components';

export const SelectWrapper = styled.div`
  display: flex;
  flex-direction: column;
  position: relative;

  select {
    font-size: 1.6rem;
    border: 0.1rem solid var(--lightblue);
    border-radius: 0.4rem;
    background-color: var(--lightgrey);
    color: var(--darkgrey);
    padding: var(--small-space) var(--smallest-space);
    -moz-appearance: none;
    -webkit-appearance: none;
  }

  &::after {
    content: ' ';
    display: block;
    position: absolute;
    top: 5.2rem;
    right: var(--smallest-space);
    width: 0;
    height: 0;
    border-left: 0.8rem solid transparent;
    border-right: 0.8rem solid transparent;
    border-top: 1.2rem solid var(--lightblue);
  }
`;
```
If you would like me to go through in more detail just let me know.

2021-01-22 11:28 UTC, vixhez commented
Thank you Rob! I will look into all of these ahead of Wednesday.

2021-01-26 16:16 UTC, closed without merging