component/BookCard
bristol-tech-fair/btf-frontend pull request #55
Opened 2021-02-01 19:12 UTC by shanesc

Closes #33 

Adds the BookCard component from the Figma design.

2021-02-01 19:23 UTC, shanesc commented
I'm not sure of the best way to pass images as props. If anyone has suggestions that would be amazing!

2021-02-01 20:46 UTC, merryface commented on src/components/BookCard/BookCard.jsx
> +  cover: PropTypes.string.isRequired
using my limited knowledge, this seems fine, it's how I did the other TWO times I've used react...

2021-02-01 20:50 UTC, merryface approved these changes, later dismissed
I can't really comment on the tests.
Didn't see anything obviously wrong (to my knowledge).
The only time I passed an image as a prop I did it this way too

2021-02-02 08:10 UTC, RobTF9 commented
The image prop needs to be a URL, as we'll most likely be serving images from an s3/cloudinary bucket.

Put the images you want to use for storybook in: `/public/assets/images/your-image.png` then pass the url to the component.

2021-02-02 10:22 UTC, shanesc commented
> The image prop needs to be a URL, as we'll most likely be serving images from an s3/cloudinary bucket.
> 
> Put the images you want to use for storybook in: `/public/assets/images/your-image.png` then pass the url to the component.

Ok will do. Will we be pulling the URL from the database in production?

The prop passed in is being used as the source URL, is that correct? If so, I'll just move the image used for Storybook as above.

2021-02-24 15:58 UTC, RobTF9 requested changes

2021-02-24 15:58 UTC, RobTF9 commented on src/components/BookCard/BookCard.styles.js
> +  background: #ffffff;
use var(--white) here

2021-02-24 15:58 UTC, RobTF9 commented on src/components/BookCard/BookCard.styles.js
> +  width: 24rem;
Don't need a width.

2021-02-24 15:58 UTC, RobTF9 commented on src/components/BookCard/BookCard.styles.js
> +  height: 30.9rem;
Don't need a height

2021-03-05 17:58 UTC, shanesc commented
Made the changes requested

2021-03-10 08:13 UTC, RobTF9 approved these changes

2021-03-10 11:33 UTC, merged