Font/karla bold
bristol-tech-fair/btf-frontend pull request #63
Opened 2021-02-11 11:11 UTC by mmkobylin

Karla bold imported and updated in index.html

2021-02-13 12:03 UTC, shanesc commented
Hi Marta, a couple of things when I tested:

1. I think the same `@font-face` code needs to be added to the `preview-head.html` file to work in Storybook. This is due to the way Storybook loads assets (https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head)
![image](https://user-images.githubusercontent.com/47223963/107849434-0eefa900-6df3-11eb-9bce-9d394153f231.png)

2. The code looks good but I think the `.woff` files are not the correct weight. I'm seeing no difference between 600, 700, and 800 in Storybook components. Let me know if you are seeing the same.

Hopefully that makes sense but ping me on Slack if you want to discuss.

2021-02-13 12:12 UTC, shanesc requested changes
Please check the `.woff` files are correct as they're not rendering bold on Storybook. Also add the `@font-face` to `preview-head.html`

2021-02-13 12:12 UTC, shanesc commented on public/index.html
> +      }
This block of code needs to be added to `.storybook/preview-head.html` as well. See https://storybook.js.org/docs/react/configure/story-rendering#adding-to-head

2021-02-15 15:28 UTC, mmkobylin commented
Hi, I have changed the files and tested them - there is a difference between using font-weight: 600 and 700. Please double check if everything looks correct.

2021-02-15 17:28 UTC, shanesc requested changes
Hi Marta, looks great and is working for me!

Just one last thing, can you please delete the `Karla-Large.woff` and `Karla-Large.woff2` files as they're not being used. Once that's done it's ready to be merged 👍

2021-02-15 17:35 UTC, shanesc approved these changes
Looks good! Squash and Merge 👍

2021-02-15 17:40 UTC, merged