Refactor/global input styles
bristol-tech-fair/btf-frontend pull request #67
Opened 2021-02-17 11:23 UTC by catherinehoward

Closes #56

This pull request adds global styles for the input components: TextArea, TextInput and Select.

2021-02-17 11:34 UTC, catherinehoward commented
I can't get StoryBook too work at the moment. I'm getting the following error:

Unable to resolve path to module './src/theme/inputs.styles'  imp
ort/no-unresolved

It doesn't like my import statement for InputWrapper in TextArea.styles.js. Can you let me know what the correct address path is? Tried a few different things!

2021-02-24 16:26 UTC, RobTF9 requested changes

2021-02-24 16:26 UTC, RobTF9 commented on src/theme/inputs.styles.js
> +    padding: var(--small-space) var(--smallest-space);
change padding to `padding: var(--small-space);` like you originally had in the TextInput component

2021-02-24 16:26 UTC, RobTF9 commented on src/theme/index.js
> +      <InputWrapper />
You don't need to import this here. You're not creating a global style.

2021-02-24 20:10 UTC, catherinehoward commented
@RobTF9 I've made those changes if you could check again. Thanks

2021-03-10 08:12 UTC, RobTF9 approved these changes

2021-03-10 17:47 UTC, merged